### ISSUE TITLE
apnar name report ache 

### ISSUE THREAD

**Issue by shipon-hossen-raju** [NazmusSayad/Git-Stats#1]
apnar k ami online a khuje pacchi na keno .... apni sob kichu disable kore rakhche ... ami folish er kache report korbo apni online a nai keno ...

**Comment by NazmusSayad** [comment]
![image](https://user-images.githubusercontent.com/87106526/205509593-00697175-789a-4d3e-b544-52420c62fe9b.png)
Ami ei group e active achi :)
